dist: trusty
language: ruby

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --disable-external ./_site

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ./bin/deploy.sh
  on:
    branch: master
