# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: '100 Warm Tunas News'
title_tag: 'News | 100 Warm Tunas'
post_title_suffix: ' | 100 Warm Tunas'
author: 100 Warm Tunas
description: >- # this means to ignore newlines until "baseurl:"
  The internet's most accurate prediction of Triple J's Hottest 100 for 2018, updated daily.
baseurl: "/news" # the subpath of your site, e.g. /blog
url: "https://100warmtunas.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
plugins:
  - jekyll-sitemap

permalink: /:year/:month/:title/

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"

destination: _site/news

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin
